"""update tasks table

Revision ID: 6dc4987ba029
Revises: b7104e2a0bb3
Create Date: 2019-05-30 13:16:34.136823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dc4987ba029'
down_revision = 'b7104e2a0bb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'func_name',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('tasks', 'func_name',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    # ### end Alembic commands ###
