"""add title, message to tasks

Revision ID: 919514e95292
Revises: 6dc4987ba029
Create Date: 2019-05-30 15:24:40.495004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '919514e95292'
down_revision = '6dc4987ba029'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('message', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('title', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'title')
    op.drop_column('tasks', 'message')
    # ### end Alembic commands ###
