"""add meta to tasks

Revision ID: e5ffc32ee0f0
Revises: 919514e95292
Create Date: 2019-05-31 07:05:30.309632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5ffc32ee0f0'
down_revision = '919514e95292'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('meta', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'meta')
    # ### end Alembic commands ###
